### PR TITLE
Deployment Process for Prod K8s

### PR DESCRIPTION
**Pull request by BogDrakonov**
Once these are merged we can deploy them to [ArgoCD](https://argocd.kodex.io/) so that the bot deploys to the `production` namespace

### CODE REVIEW

**Comment by BogDrakonov** [comment]
@perpetuum7 Do any ports or APIs need exposing for this particular container when it runs in K8s? If so which ones? I will create the service.yml for that, and then I think we can test migrating this over

**Comment by perpetuum7** [comment]
> @perpetuum7 Do any ports or APIs need exposing for this particular container when it runs in K8s? If so which ones? I will create the service.yml for that, and then I think we can test migrating this over

Nope, no ports are needed.

**Review by perpetuum7 — CHANGES_REQUESTED** [review]
Could you just replace `ethereum-nft-sales-bot` with `kodex-sales-notification`, please.

**Comment by BogDrakonov** [comment]
> Could you just replace `ethereum-nft-sales-bot` with `kodex-sales-notification`, please.

Yeah I can do a string replace on those in my next commit.

**Review by perpetuum7 — APPROVED** [review]

**Pull request merged**
